### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Wojciech-A** [baibai25/horse-pose-estimation#1]
Hello,

Very great job! 

The repository does not contain information about license. What is the type of license for your model?

**Comment by baibai25** [comment]
@Wojciech-A 
Hi!

Thank you for your comment!

In this proect, I used [DeepLabCut](https://github.com/DeepLabCut/DeepLabCut) and [mmpose](https://github.com/open-mmlab/mmpose).
Therefore, the license follows these libraries. Please check each repository.

If you have any questions about my code, feel free to message me!

Thank you.
